### ISSUE TITLE
Include Cache-Control Headers

### ISSUE THREAD

**Issue by kespinola** [holaplex/imgopt#1]
### Background

When the service being proxied by cloudflare sets Cache-Control header cloudflare will forward the header along to the browser which triggers it to lookup the context from its local cache instead of requesting from cloudflare.
<img width="479" alt="Screen Shot 2022-03-22 at 6 27 43 AM" src="https://user-images.githubusercontent.com/2388118/159492823-9cb2d863-5ff4-458c-991e-6de3583400c4.png">

### Goal 

Users that have viewed an image before from their browser serve images from local cache instead of requesting again from cloudflare.

### Requirements

When image successfully resized set Cache-Control header max-age to trigger local cache lookups from a browser.

https://github.com/holaplex/holaplex/blob/dev/pages/api/arweave/txt/%5Bid%5D.ts#L45

**Comment by mpwsh** [comment]
Added Cache Control headers to each response after image has been download/resized.

See PR #2   

I can see images being cached by the browser.
