### ISSUE TITLE
Serve IPFS Images from Assets Proxy

### ISSUE THREAD

**Issue by kespinola** [holaplex/imgopt#21]
## Goal
Any images we store on ipfs should be referenced through the asset proxy.

## Examples
- [x] NFT image
- [x] Organization profile image
- [x] Project profile image

## Requirement
Add customer field resolver for each field that replace ipfs link with asset proxy link.

**Comment by imabdulbasit** [comment]
https://github.com/holaplex/hub-orgs/pull/81
https://github.com/holaplex/hub-nfts/pull/75
