### ISSUE TITLE
Track Requested URLs

### ISSUE THREAD

**Issue by kespinola** [holaplex/imgopt#9]
### Goal
Prevent continual requesting of "bad" URLs to prevent excessive NAT costs from reaching out to the Internet for content that does not exist.

### Requirements
- imgopt tracks when an asset url is unresolvable (ie 4xx, 5xx)
- imgopt updates attempts to fetch an asset url that is unresolvable
- imgopt configured for max retries to asset urls
- imgopt looks up the asset url in its internal asset store before requesting the asset from the Internet.
- imgopt returns error to the caller instead of requesting from asset source when the asset has exceeded its maximum fetch attempts

### Tasks
- [x] Document strategy for request URL tracking in Notion tech spec

**Comment by mpwsh** [comment]
Tech spec with implementation available at: 
https://www.notion.so/holaplex/Tracking-of-external-asset-URLs-f378ef3a060342279966455f8b366c3f

**Comment by kespinola** [comment]
so good. ty.
